### ISSUE TITLE
Spyro 3 PAL

### ISSUE THREAD

**Issue by retrofank** [alex-free/libcrypt-patcher#3]
Hi,

First off, would like to thank you for creating this easy to use tool.  Having to search and download individual scene cracks can be cumbersome and time consuming.   

However, did you properly fix Spyro 3's LC?   The scene crack by paradox for 1.0 was never fully 100% cracked, as I tested it some years back on a PSIO ODE and the running an illegal copy message appeared and this particular game was notorious out of them all. 

I also, noticed that the 1.1 version of Spyro 3 is now supported, which was never done all those years ago,

Regards

**Comment by alex-free** [comment]
> Hi,
> 
> 
> 
> First off, would like to thank you for creating this easy to use tool.  Having to search and download individual scene cracks can be cumbersome and time consuming.   
> 
> 
> 
> However, did you fix properly fix Spyro 3's LC?   The scene crack by paradox for 1.0 was never fully 100% cracked, as I tested it some years back on a PSIO ODE and the running an illegal copy message appeared and this particular game was notorious out of them all. 
> 
> 
> 
> I also, noticed that the 1.1 version of Spyro 3 is now supported, which was never done all those years ago,
> 
> 
> 
> Regards
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

I implemented the newer Agrippa cracks for LibCrypt Patcher that fixes all the paradox crack issues, and also provided support for v1.1. Also used Agrippa patch for Sydney 2000 IIRC https://www.psx-place.com/threads/ps1-libcrypt-support-on-ps3-official-emus-research-thread.35836/page-14

**Comment by alex-free** [comment]
If any issues are experienced with these games feel free to open a new issue or re-open this one ;)
