### ISSUE TITLE
Overblood 2 crash

### ISSUE THREAD

**Issue by Littlemouse1968** [alex-free/libcrypt-patcher#5]
If your tool is used with "OverBlood 2 (Europe) v1.0", the game will crash. This is because you are using the wrong patch.
Overblood 2 v1.0 has a bug that prevents you from completing the game. The game crashes in the second episode because the developer left the Libcrypt routine in the executable (magic word is 0x0000). This bug was fixed with the second release of the UK version (v1.1).
In the following link you'll find a zip file with the savegames just before the "game ending bug" (when you try to open the door, the game freezes) and the patches for the European 1.0 version (v1.1 doesn't need it) and for the Italian version. 

https://www.mediafire.com/file/bnx2kv4zvzlt1mb

For the Italian version, your tool uses brill's patch, which works because it uses MW 0x0000. However, I think it's better to use the one I've provided (which is based on BAD's patch) because it skips the libcrypt routine completely.
 
Bye

PS: In the zip file you will also find links to your "Wanted Games" with the corresponding patches and for Final Fantasy VIII (these only patch libcrypt without any additional changes).

**Comment by alex-free** [comment]
> If your tool is used with "OverBlood 2 (Europe) v1.0", the game will crash. This is because you are using the wrong patch. Overblood 2 v1.0 has a bug that prevents you from completing the game. The game crashes in the second episode because the developer left the Libcrypt routine in the executable (magic word is 0x0000). This bug was fixed with the second release of the UK version (v1.1). In the following link you'll find a zip file with the savegames just before the "game ending bug" (when you try to open the door, the game freezes) and the patches for the European 1.0 version (v1.1 doesn't need it) and for the Italian version.
> 
> https://www.mediafire.com/file/bnx2kv4zvzlt1mb
> 
> For the Italian version, your tool uses brill's patch, which works because it uses MW 0x0000. However, I think it's better to use the one I've provided (which is based on BAD's patch) because it skips the libcrypt routine completely.
> 
> Bye
> 
> PS: In the zip file you will also find links to your "Wanted Games" with the corresponding patches and for Final Fantasy VIII (these only patch libcrypt without any additional changes).

Your a G... I implemented all the revised patched for FF VIII and fixed OverBlood 2 Europe, please check out v1.0.5 :)

Haha thought only Jakie Chan had broken LibCrypt protection, Sony QA sucked... did they like play the game past level 1?

I will get around to the other 'wanted games' asap... thank you soo much for this info and report.

**Comment by alex-free** [comment]
Thanks for all your help. All of these patches have been added as of v1.0.6. We are now at 236 supported game disc images. The only game I know of that isn't supported is: https://hiddenpalace.org/Formula_One_99_(Aug_12,_1999_prototype) because I don't have a patch, I think it may have never been patched.
