### ISSUE TITLE
Formula One 99 (Aug 12, 1999 prototype)

### ISSUE THREAD

**Issue by Littlemouse1968** [alex-free/libcrypt-patcher#6]
You said you didn't have the patch for "Formula One 99 (Aug 12, 1999 prototype)".
Here is mine...

https://www.mediafire.com/file/epedf8h3i3idgwk

Littlemouse

PS: Please note that to run the game with Duckstation, you have to manually enable "Interpreter Mode" (Settings-->Console - CPU Emulation - Execution Mode: Interpreter), otherwise the game will freeze while loading.

**Comment by alex-free** [comment]
> You said you didn't have the patch for "Formula One 99 (Aug 12, 1999 prototype)". Here is mine...
> 
> https://www.mediafire.com/file/epedf8h3i3idgwk
> 
> Littlemouse
> 
> PS: Please note that to run the game with Duckstation, you have to manually enable "Interpreter Mode" (Settings-->Console - CPU Emulation - Execution Mode: Interpreter), otherwise the game will freeze while loading.

Thanks, just added this to v1.0.7!
