### ISSUE TITLE
FINAL FANTASY IX DISC SWAP

### ISSUE THREAD

**Issue by andreinkho89** [alex-free/libcrypt-patcher#7]
Good morning. For the Italian version of Final Fantasy IX I tried to see if the change of the disc works on Duckstation. If I start the disc 2 patched and select new game it asks me for cd 1. If I select the patched cd 1 however it loads it but the screen remains black with music and does not load the first cd intro. It wanted to be a test to see if the patch worked with multi-disk games. I'm afraid that starting the game, when he asks me to insert disc 2 the error will occur. How can I solve it?

**Comment by alex-free** [comment]
> Good morning. For the Italian version of Final Fantasy IX I tried to see if the change of the disc works on Duckstation. If I start the disc 2 patched and select new game it asks me for cd 1. If I select the patched cd 1 however it loads it but the screen remains black with music and does not load the first cd intro. It wanted to be a test to see if the patch worked with multi-disk games. I'm afraid that starting the game, when he asks me to insert disc 2 the error will occur. How can I solve it?

The patcher works with other multi-disc games. The patch for Final Fantasy IX's  is causing this issue for only this game specifically. I believe you can save your progress on disc 1 before Final Fantasy IX will ask you for disc 2. Then you can reset and boot disc 2, and continue the save made on disc 1. 

Some other PSX games (like Fear Effect and Parasite Eve) force you to swap the disc without such an option being available (to load the  last save made on disc 1 with disc 2). But I believe Final Fantasy IX is not like that and the above would work.

I must change the patch to get the disc change part working. I will let you know when the update is available.

**Comment by andreinkho89** [comment]
Hello.
Thank you for your response.

Meanwhile, I also tested Parasite Eve II with patch applied, using the duckstation emulator.
I can confirm that the latter works perfectly, so as you said the problem only afflicts the Italian version of FF IX.
I await your updates, thanking you for all the immense work you have done.

**Comment by alex-free** [comment]
@andreinkho89  You can use LibCrypt patcher right now to play Final Fantasy 9 follow these steps. Please let me know if you understand these Final Fantasy 9 specific instructions. This is only needed for Final Fantasy 9 to complete the game patched with LibCrypt Patcher:

1) Patch all disc images with LibCrypt Patcher (CD 1/CD 2/CD 3/CD 4).
2) Boot disc 1
3) Save game at end of disc 1 when asked by the game. this is immediately before the disc swap message appears in game asking for disc 2.
4)  When asked for disc 2, turn off your console.
5) Remove disc 1 and put in disc 2 with the console off.
6) Start your console with disc 2.
7) Load your save game on disc 2 and continue.

This works for CD 2/CD 3/CD 4 in Final Fantasy 9 with the current LibCrypt Patcher.

I got this info from https://gamefaqs.gamespot.com/boards/197338-final-fantasy-ix/47693269

It appears all other existing patches for Final Fantasy 9 require this, at least https://dl.consolecopyworld.com/?id=psx&file=hydff9fr!zip also does (from https://consolecopyworld.com/psx/psx_patches_f.shtml).

**Comment by Littlemouse1968** [comment]
Please find below the link to new Final Fantasy 9 patches. They should still work after changing the disc.

https://www.mediafire.com/file/0701zsls85tl8wy

**Comment by alex-free** [comment]
> Please find below the link to new Final Fantasy 9 patches. They should still work after changing the disc.
> 
> https://www.mediafire.com/file/0701zsls85tl8wy

Confirmed, these are the only patches that actually work 100%! thanks, added to v1.0.8 update.

@andreinkho89 thank you for pointing out this issue. If you patch Final Fantasy XI with the latest LibCrypt Patcher v1.0.9 it now works correctly when switching discs!
