### ISSUE TITLE
ToCA World Touring Cars PAL (Es,It) locks

### ISSUE THREAD

**Issue by CometHunter92** [alex-free/libcrypt-patcher#9]
Hi, I patched a redump verified backup with this tool, launched on a PAL SCPH 7502 PS1 with Unirom and it works, but the game locks everytime you try to enter the "quick race", the one with random car/track choice. Didn't test it extensively, but normal race mode, time attack and so on work well without issues. Original game doesn't exhibit this issue.

**Comment by alex-free** [comment]
Hm, works with DuckStation. I wonder if there are some additional EDC related shananigans. http://redump.org/disc/27567/ mentions EDC, it is possible that the original patch didn't handle that so on real hardware you get the lock. I'll have to try that out next.

**Comment by alex-free** [comment]
Without patching , DuckStation gets stuck here:
![Screenshot from 2024-08-08 08-36-47](https://github.com/user-attachments/assets/4e6cf25d-0a58-406e-a828-3aa9265610a0)

**Comment by CometHunter92** [comment]
Tried the game without the patch/sbi file in DuckStation: it locks "correctly" when loading game modes.
Tried the patched game and it loads the "quick race" event correctly.
Ripped back the burned disc I use on my PSX and it too correctly works in DuckStation (the MD5 checksum is the same as the patched file on my PC, so no write errors/weird write corrections during the burn).

**Comment by alex-free** [comment]
> Tried the game without the patch/sbi file in DuckStation: it locks "correctly" when loading game modes. Tried the patched game and it loads the "quick race" event correctly. Ripped back the burned disc I use on my PSX and it too correctly works in DuckStation (the MD5 checksum is the same as the patched file on my PC, so no write errors/weird write corrections during the burn). It's something that only happens on real hardware so (at least on my PSX).

Looks like I’ll need to investigate on real hardware. Did you try with any other softmods other than UniROM? Do you have another console to try with?

**Comment by CometHunter92** [comment]
I'm short of memory cards, so I can't try other softmods now, and I only have one PSX right now here... I don't know if it's an issue related to my specific setup. Let me know.

**Comment by alex-free** [comment]
> I'm short of memory cards, so I can't try other softmods now, and I only have one PSX right now here... I don't know if it's an issue related to my specific setup. Let me know.

Just trying to rule things out. I’m gonna test out on my various consoles.

**Comment by alex-free** [comment]
@CometHunter92 I tried the game using a SCPH-90001 PS2 and it worked just fine with the patch applied. I still need to try on a PSX console. To further debug this, I have some questions:

1) What CD-R media are you using (brand name/manufacturer)?
2) What burner are you using?
3) What burning software are you using? (although this shouldn't matter since you ripped back the image, just curious really).
4) Have you tried flipping the PSX console vertically after closing the lid and booting with UNIROM so that the console is standing on it's side? Try both left and right orientations, it may be a disc read issue related to the CD-R (that doesn't occur on real pressed CD-ROMs).
5) Have you tried burning the disc at differnet speeds?

**Comment by CometHunter92** [comment]
> @CometHunter92 I tried the game using a SCPH-90001 PS2 and it worked just fine with the patch applied. I still need to try on a PSX console. To further debug this, I have some questions:
> 
> 1. What CD-R media are you using (brand name/manufacturer)?
> 2. What burner are you using?
> 3. What burning software are you using? (although this shouldn't matter since you ripped back the image, just curious really).
> 4. Have you tried flipping the PSX console vertically after closing the lid and booting with UNIROM so that the console is standing on it's side? Try both left and right orientations, it may be a disc read issue related to the CD-R (that doesn't occur on real pressed CD-ROMs).
> 5. Have you tried burning the disc at differnet speeds?

1) Verbatim CD-R AZO (Mitsubishi)
2) I'm using the burner in a 2010 Unibody MacBook, a SuperDrive (I need to check the manufacturer).
3) ImgBurn (DAO/SAO mode).
4) Not yet.
5) I burn always at the slowest speed possible on my setup (8x) and I didn't have problems yet with a PSX and a Saturn. 

I need to check with a different controller, I remember a DualShock that made the games to hang in certain points when plugged in. (My control ports are a little bit finnicky). I'm curious if TonyHax International would work.

**Comment by alex-free** [comment]
> > @CometHunter92 I tried the game using a SCPH-90001 PS2 and it worked just fine with the patch applied. I still need to try on a PSX console. To further debug this, I have some questions:
> 
> > 
> 
> > 1. What CD-R media are you using (brand name/manufacturer)?
> 
> > 2. What burner are you using?
> 
> > 3. What burning software are you using? (although this shouldn't matter since you ripped back the image, just curious really).
> 
> > 4. Have you tried flipping the PSX console vertically after closing the lid and booting with UNIROM so that the console is standing on it's side? Try both left and right orientations, it may be a disc read issue related to the CD-R (that doesn't occur on real pressed CD-ROMs).
> 
> > 5. Have you tried burning the disc at differnet speeds?
> 
> 
> 
> 1) Verbatim CD-R AZO (Mitsubishi)
> 
> 2) I'm using the burner in a 2010 Unibody MacBook, a SuperDrive (I need to check the manufacturer).
> 
> 3) ImgBurn (DAO/SAO mode).
> 
> 4) Not yet.
> 
> 5) I burn always at the slowest speed possible on my setup (8x) and I didn't have problems yet with a PSX and a Saturn. 
> 
> 
> 
> I need to check with a different controller, I remember a DualShock that made the games to hang in certain points when plugged in. (My control ports are a little bit finnicky). I'm curious if TonyHax International would work.

If you can at all please try with an older burner and or different burn speeds. It can make a difference.

**Comment by alex-free** [comment]
Just tried the CD-R on my SCPH-1000 PS1 and it worked fine. Since this is likely a disc read issue, I will be closing it.
